/*
Fideo Production API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.4
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SignalPatternsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignalPatternsRequest{}

// SignalPatternsRequest struct for SignalPatternsRequest
type SignalPatternsRequest struct {
	// Email address to get signal patterns for
	Email string `json:"email"`
	// Time interval for timeseries data (used only for timeseries endpoint)
	Interval *string `json:"interval,omitempty"`
	// Number of data points to return (used only for timeseries endpoint)
	Count *int32 `json:"count,omitempty"`
}

type _SignalPatternsRequest SignalPatternsRequest

// NewSignalPatternsRequest instantiates a new SignalPatternsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignalPatternsRequest(email string) *SignalPatternsRequest {
	this := SignalPatternsRequest{}
	this.Email = email
	return &this
}

// NewSignalPatternsRequestWithDefaults instantiates a new SignalPatternsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignalPatternsRequestWithDefaults() *SignalPatternsRequest {
	this := SignalPatternsRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *SignalPatternsRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *SignalPatternsRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *SignalPatternsRequest) SetEmail(v string) {
	o.Email = v
}

// GetInterval returns the Interval field value if set, zero value otherwise.
func (o *SignalPatternsRequest) GetInterval() string {
	if o == nil || IsNil(o.Interval) {
		var ret string
		return ret
	}
	return *o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalPatternsRequest) GetIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.Interval) {
		return nil, false
	}
	return o.Interval, true
}

// HasInterval returns a boolean if a field has been set.
func (o *SignalPatternsRequest) HasInterval() bool {
	if o != nil && !IsNil(o.Interval) {
		return true
	}

	return false
}

// SetInterval gets a reference to the given string and assigns it to the Interval field.
func (o *SignalPatternsRequest) SetInterval(v string) {
	o.Interval = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *SignalPatternsRequest) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalPatternsRequest) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *SignalPatternsRequest) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *SignalPatternsRequest) SetCount(v int32) {
	o.Count = &v
}

func (o SignalPatternsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignalPatternsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if !IsNil(o.Interval) {
		toSerialize["interval"] = o.Interval
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

func (o *SignalPatternsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignalPatternsRequest := _SignalPatternsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignalPatternsRequest)

	if err != nil {
		return err
	}

	*o = SignalPatternsRequest(varSignalPatternsRequest)

	return err
}

type NullableSignalPatternsRequest struct {
	value *SignalPatternsRequest
	isSet bool
}

func (v NullableSignalPatternsRequest) Get() *SignalPatternsRequest {
	return v.value
}

func (v *NullableSignalPatternsRequest) Set(val *SignalPatternsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSignalPatternsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSignalPatternsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignalPatternsRequest(val *SignalPatternsRequest) *NullableSignalPatternsRequest {
	return &NullableSignalPatternsRequest{value: val, isSet: true}
}

func (v NullableSignalPatternsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignalPatternsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


