/*
Fideo API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.4
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
)

// checks if the SignalPatternRecencyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignalPatternRecencyResponse{}

// SignalPatternRecencyResponse struct for SignalPatternRecencyResponse
type SignalPatternRecencyResponse struct {
	Hour *SignalPatternResponseUnit `json:"hour,omitempty"`
	Day *SignalPatternResponseUnit `json:"day,omitempty"`
	Week *SignalPatternResponseUnit `json:"week,omitempty"`
	Month *SignalPatternResponseUnit `json:"month,omitempty"`
	SixMonth *SignalPatternResponseUnit `json:"sixMonth,omitempty"`
	Year *SignalPatternResponseUnit `json:"year,omitempty"`
}

// NewSignalPatternRecencyResponse instantiates a new SignalPatternRecencyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignalPatternRecencyResponse() *SignalPatternRecencyResponse {
	this := SignalPatternRecencyResponse{}
	return &this
}

// NewSignalPatternRecencyResponseWithDefaults instantiates a new SignalPatternRecencyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignalPatternRecencyResponseWithDefaults() *SignalPatternRecencyResponse {
	this := SignalPatternRecencyResponse{}
	return &this
}

// GetHour returns the Hour field value if set, zero value otherwise.
func (o *SignalPatternRecencyResponse) GetHour() SignalPatternResponseUnit {
	if o == nil || IsNil(o.Hour) {
		var ret SignalPatternResponseUnit
		return ret
	}
	return *o.Hour
}

// GetHourOk returns a tuple with the Hour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalPatternRecencyResponse) GetHourOk() (*SignalPatternResponseUnit, bool) {
	if o == nil || IsNil(o.Hour) {
		return nil, false
	}
	return o.Hour, true
}

// HasHour returns a boolean if a field has been set.
func (o *SignalPatternRecencyResponse) HasHour() bool {
	if o != nil && !IsNil(o.Hour) {
		return true
	}

	return false
}

// SetHour gets a reference to the given SignalPatternResponseUnit and assigns it to the Hour field.
func (o *SignalPatternRecencyResponse) SetHour(v SignalPatternResponseUnit) {
	o.Hour = &v
}

// GetDay returns the Day field value if set, zero value otherwise.
func (o *SignalPatternRecencyResponse) GetDay() SignalPatternResponseUnit {
	if o == nil || IsNil(o.Day) {
		var ret SignalPatternResponseUnit
		return ret
	}
	return *o.Day
}

// GetDayOk returns a tuple with the Day field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalPatternRecencyResponse) GetDayOk() (*SignalPatternResponseUnit, bool) {
	if o == nil || IsNil(o.Day) {
		return nil, false
	}
	return o.Day, true
}

// HasDay returns a boolean if a field has been set.
func (o *SignalPatternRecencyResponse) HasDay() bool {
	if o != nil && !IsNil(o.Day) {
		return true
	}

	return false
}

// SetDay gets a reference to the given SignalPatternResponseUnit and assigns it to the Day field.
func (o *SignalPatternRecencyResponse) SetDay(v SignalPatternResponseUnit) {
	o.Day = &v
}

// GetWeek returns the Week field value if set, zero value otherwise.
func (o *SignalPatternRecencyResponse) GetWeek() SignalPatternResponseUnit {
	if o == nil || IsNil(o.Week) {
		var ret SignalPatternResponseUnit
		return ret
	}
	return *o.Week
}

// GetWeekOk returns a tuple with the Week field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalPatternRecencyResponse) GetWeekOk() (*SignalPatternResponseUnit, bool) {
	if o == nil || IsNil(o.Week) {
		return nil, false
	}
	return o.Week, true
}

// HasWeek returns a boolean if a field has been set.
func (o *SignalPatternRecencyResponse) HasWeek() bool {
	if o != nil && !IsNil(o.Week) {
		return true
	}

	return false
}

// SetWeek gets a reference to the given SignalPatternResponseUnit and assigns it to the Week field.
func (o *SignalPatternRecencyResponse) SetWeek(v SignalPatternResponseUnit) {
	o.Week = &v
}

// GetMonth returns the Month field value if set, zero value otherwise.
func (o *SignalPatternRecencyResponse) GetMonth() SignalPatternResponseUnit {
	if o == nil || IsNil(o.Month) {
		var ret SignalPatternResponseUnit
		return ret
	}
	return *o.Month
}

// GetMonthOk returns a tuple with the Month field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalPatternRecencyResponse) GetMonthOk() (*SignalPatternResponseUnit, bool) {
	if o == nil || IsNil(o.Month) {
		return nil, false
	}
	return o.Month, true
}

// HasMonth returns a boolean if a field has been set.
func (o *SignalPatternRecencyResponse) HasMonth() bool {
	if o != nil && !IsNil(o.Month) {
		return true
	}

	return false
}

// SetMonth gets a reference to the given SignalPatternResponseUnit and assigns it to the Month field.
func (o *SignalPatternRecencyResponse) SetMonth(v SignalPatternResponseUnit) {
	o.Month = &v
}

// GetSixMonth returns the SixMonth field value if set, zero value otherwise.
func (o *SignalPatternRecencyResponse) GetSixMonth() SignalPatternResponseUnit {
	if o == nil || IsNil(o.SixMonth) {
		var ret SignalPatternResponseUnit
		return ret
	}
	return *o.SixMonth
}

// GetSixMonthOk returns a tuple with the SixMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalPatternRecencyResponse) GetSixMonthOk() (*SignalPatternResponseUnit, bool) {
	if o == nil || IsNil(o.SixMonth) {
		return nil, false
	}
	return o.SixMonth, true
}

// HasSixMonth returns a boolean if a field has been set.
func (o *SignalPatternRecencyResponse) HasSixMonth() bool {
	if o != nil && !IsNil(o.SixMonth) {
		return true
	}

	return false
}

// SetSixMonth gets a reference to the given SignalPatternResponseUnit and assigns it to the SixMonth field.
func (o *SignalPatternRecencyResponse) SetSixMonth(v SignalPatternResponseUnit) {
	o.SixMonth = &v
}

// GetYear returns the Year field value if set, zero value otherwise.
func (o *SignalPatternRecencyResponse) GetYear() SignalPatternResponseUnit {
	if o == nil || IsNil(o.Year) {
		var ret SignalPatternResponseUnit
		return ret
	}
	return *o.Year
}

// GetYearOk returns a tuple with the Year field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalPatternRecencyResponse) GetYearOk() (*SignalPatternResponseUnit, bool) {
	if o == nil || IsNil(o.Year) {
		return nil, false
	}
	return o.Year, true
}

// HasYear returns a boolean if a field has been set.
func (o *SignalPatternRecencyResponse) HasYear() bool {
	if o != nil && !IsNil(o.Year) {
		return true
	}

	return false
}

// SetYear gets a reference to the given SignalPatternResponseUnit and assigns it to the Year field.
func (o *SignalPatternRecencyResponse) SetYear(v SignalPatternResponseUnit) {
	o.Year = &v
}

func (o SignalPatternRecencyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignalPatternRecencyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hour) {
		toSerialize["hour"] = o.Hour
	}
	if !IsNil(o.Day) {
		toSerialize["day"] = o.Day
	}
	if !IsNil(o.Week) {
		toSerialize["week"] = o.Week
	}
	if !IsNil(o.Month) {
		toSerialize["month"] = o.Month
	}
	if !IsNil(o.SixMonth) {
		toSerialize["sixMonth"] = o.SixMonth
	}
	if !IsNil(o.Year) {
		toSerialize["year"] = o.Year
	}
	return toSerialize, nil
}

type NullableSignalPatternRecencyResponse struct {
	value *SignalPatternRecencyResponse
	isSet bool
}

func (v NullableSignalPatternRecencyResponse) Get() *SignalPatternRecencyResponse {
	return v.value
}

func (v *NullableSignalPatternRecencyResponse) Set(val *SignalPatternRecencyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSignalPatternRecencyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSignalPatternRecencyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignalPatternRecencyResponse(val *SignalPatternRecencyResponse) *NullableSignalPatternRecencyResponse {
	return &NullableSignalPatternRecencyResponse{value: val, isSet: true}
}

func (v NullableSignalPatternRecencyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignalPatternRecencyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


