/*
Fideo API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.3
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
)

// checks if the MultiFieldReqWithOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultiFieldReqWithOptions{}

// MultiFieldReqWithOptions struct for MultiFieldReqWithOptions
type MultiFieldReqWithOptions struct {
	Twitter *string `json:"twitter,omitempty"`
	Linkedin *string `json:"linkedin,omitempty"`
	RecordId *string `json:"recordId,omitempty"`
	PersonId *string `json:"personId,omitempty"`
	PartnerId *string `json:"partnerId,omitempty"`
	Location *LocationReq `json:"location,omitempty"`
	Avatar *string `json:"avatar,omitempty"`
	Website *string `json:"website,omitempty"`
	Title *string `json:"title,omitempty"`
	Organization *string `json:"organization,omitempty"`
	Emails []string `json:"emails,omitempty"`
	Phones []string `json:"phones,omitempty"`
	Profiles []SocialProfileReq `json:"profiles,omitempty"`
	Maids []string `json:"maids,omitempty"`
	Name *PersonNameReq `json:"name,omitempty"`
	PartnerKeys *map[string]string `json:"partnerKeys,omitempty"`
	LiNonid *string `json:"li_nonid,omitempty"`
	PanoramaId *string `json:"panoramaId,omitempty"`
	Placekey *string `json:"placekey,omitempty"`
	GeneratePid *bool `json:"generatePid,omitempty"`
	Email *string `json:"email,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Profile *SocialProfileReq `json:"profile,omitempty"`
	Maid *string `json:"maid,omitempty"`
	Infer *bool `json:"infer,omitempty"`
	Confidence *string `json:"confidence,omitempty"`
	Birthday *string `json:"birthday,omitempty"`
	IpAddress *string `json:"ipAddress,omitempty"`
	Countries []string `json:"countries,omitempty"`
	ExcludeCountries []string `json:"excludeCountries,omitempty"`
}

// NewMultiFieldReqWithOptions instantiates a new MultiFieldReqWithOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultiFieldReqWithOptions() *MultiFieldReqWithOptions {
	this := MultiFieldReqWithOptions{}
	return &this
}

// NewMultiFieldReqWithOptionsWithDefaults instantiates a new MultiFieldReqWithOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultiFieldReqWithOptionsWithDefaults() *MultiFieldReqWithOptions {
	this := MultiFieldReqWithOptions{}
	return &this
}

// GetTwitter returns the Twitter field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetTwitter() string {
	if o == nil || IsNil(o.Twitter) {
		var ret string
		return ret
	}
	return *o.Twitter
}

// GetTwitterOk returns a tuple with the Twitter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetTwitterOk() (*string, bool) {
	if o == nil || IsNil(o.Twitter) {
		return nil, false
	}
	return o.Twitter, true
}

// HasTwitter returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasTwitter() bool {
	if o != nil && !IsNil(o.Twitter) {
		return true
	}

	return false
}

// SetTwitter gets a reference to the given string and assigns it to the Twitter field.
func (o *MultiFieldReqWithOptions) SetTwitter(v string) {
	o.Twitter = &v
}

// GetLinkedin returns the Linkedin field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetLinkedin() string {
	if o == nil || IsNil(o.Linkedin) {
		var ret string
		return ret
	}
	return *o.Linkedin
}

// GetLinkedinOk returns a tuple with the Linkedin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetLinkedinOk() (*string, bool) {
	if o == nil || IsNil(o.Linkedin) {
		return nil, false
	}
	return o.Linkedin, true
}

// HasLinkedin returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasLinkedin() bool {
	if o != nil && !IsNil(o.Linkedin) {
		return true
	}

	return false
}

// SetLinkedin gets a reference to the given string and assigns it to the Linkedin field.
func (o *MultiFieldReqWithOptions) SetLinkedin(v string) {
	o.Linkedin = &v
}

// GetRecordId returns the RecordId field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetRecordId() string {
	if o == nil || IsNil(o.RecordId) {
		var ret string
		return ret
	}
	return *o.RecordId
}

// GetRecordIdOk returns a tuple with the RecordId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetRecordIdOk() (*string, bool) {
	if o == nil || IsNil(o.RecordId) {
		return nil, false
	}
	return o.RecordId, true
}

// HasRecordId returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasRecordId() bool {
	if o != nil && !IsNil(o.RecordId) {
		return true
	}

	return false
}

// SetRecordId gets a reference to the given string and assigns it to the RecordId field.
func (o *MultiFieldReqWithOptions) SetRecordId(v string) {
	o.RecordId = &v
}

// GetPersonId returns the PersonId field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetPersonId() string {
	if o == nil || IsNil(o.PersonId) {
		var ret string
		return ret
	}
	return *o.PersonId
}

// GetPersonIdOk returns a tuple with the PersonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetPersonIdOk() (*string, bool) {
	if o == nil || IsNil(o.PersonId) {
		return nil, false
	}
	return o.PersonId, true
}

// HasPersonId returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasPersonId() bool {
	if o != nil && !IsNil(o.PersonId) {
		return true
	}

	return false
}

// SetPersonId gets a reference to the given string and assigns it to the PersonId field.
func (o *MultiFieldReqWithOptions) SetPersonId(v string) {
	o.PersonId = &v
}

// GetPartnerId returns the PartnerId field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetPartnerId() string {
	if o == nil || IsNil(o.PartnerId) {
		var ret string
		return ret
	}
	return *o.PartnerId
}

// GetPartnerIdOk returns a tuple with the PartnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetPartnerIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartnerId) {
		return nil, false
	}
	return o.PartnerId, true
}

// HasPartnerId returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasPartnerId() bool {
	if o != nil && !IsNil(o.PartnerId) {
		return true
	}

	return false
}

// SetPartnerId gets a reference to the given string and assigns it to the PartnerId field.
func (o *MultiFieldReqWithOptions) SetPartnerId(v string) {
	o.PartnerId = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetLocation() LocationReq {
	if o == nil || IsNil(o.Location) {
		var ret LocationReq
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetLocationOk() (*LocationReq, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given LocationReq and assigns it to the Location field.
func (o *MultiFieldReqWithOptions) SetLocation(v LocationReq) {
	o.Location = &v
}

// GetAvatar returns the Avatar field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetAvatar() string {
	if o == nil || IsNil(o.Avatar) {
		var ret string
		return ret
	}
	return *o.Avatar
}

// GetAvatarOk returns a tuple with the Avatar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetAvatarOk() (*string, bool) {
	if o == nil || IsNil(o.Avatar) {
		return nil, false
	}
	return o.Avatar, true
}

// HasAvatar returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasAvatar() bool {
	if o != nil && !IsNil(o.Avatar) {
		return true
	}

	return false
}

// SetAvatar gets a reference to the given string and assigns it to the Avatar field.
func (o *MultiFieldReqWithOptions) SetAvatar(v string) {
	o.Avatar = &v
}

// GetWebsite returns the Website field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetWebsite() string {
	if o == nil || IsNil(o.Website) {
		var ret string
		return ret
	}
	return *o.Website
}

// GetWebsiteOk returns a tuple with the Website field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetWebsiteOk() (*string, bool) {
	if o == nil || IsNil(o.Website) {
		return nil, false
	}
	return o.Website, true
}

// HasWebsite returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasWebsite() bool {
	if o != nil && !IsNil(o.Website) {
		return true
	}

	return false
}

// SetWebsite gets a reference to the given string and assigns it to the Website field.
func (o *MultiFieldReqWithOptions) SetWebsite(v string) {
	o.Website = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *MultiFieldReqWithOptions) SetTitle(v string) {
	o.Title = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetOrganization() string {
	if o == nil || IsNil(o.Organization) {
		var ret string
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetOrganizationOk() (*string, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given string and assigns it to the Organization field.
func (o *MultiFieldReqWithOptions) SetOrganization(v string) {
	o.Organization = &v
}

// GetEmails returns the Emails field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetEmails() []string {
	if o == nil || IsNil(o.Emails) {
		var ret []string
		return ret
	}
	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetEmailsOk() ([]string, bool) {
	if o == nil || IsNil(o.Emails) {
		return nil, false
	}
	return o.Emails, true
}

// HasEmails returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasEmails() bool {
	if o != nil && !IsNil(o.Emails) {
		return true
	}

	return false
}

// SetEmails gets a reference to the given []string and assigns it to the Emails field.
func (o *MultiFieldReqWithOptions) SetEmails(v []string) {
	o.Emails = v
}

// GetPhones returns the Phones field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetPhones() []string {
	if o == nil || IsNil(o.Phones) {
		var ret []string
		return ret
	}
	return o.Phones
}

// GetPhonesOk returns a tuple with the Phones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetPhonesOk() ([]string, bool) {
	if o == nil || IsNil(o.Phones) {
		return nil, false
	}
	return o.Phones, true
}

// HasPhones returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasPhones() bool {
	if o != nil && !IsNil(o.Phones) {
		return true
	}

	return false
}

// SetPhones gets a reference to the given []string and assigns it to the Phones field.
func (o *MultiFieldReqWithOptions) SetPhones(v []string) {
	o.Phones = v
}

// GetProfiles returns the Profiles field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetProfiles() []SocialProfileReq {
	if o == nil || IsNil(o.Profiles) {
		var ret []SocialProfileReq
		return ret
	}
	return o.Profiles
}

// GetProfilesOk returns a tuple with the Profiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetProfilesOk() ([]SocialProfileReq, bool) {
	if o == nil || IsNil(o.Profiles) {
		return nil, false
	}
	return o.Profiles, true
}

// HasProfiles returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasProfiles() bool {
	if o != nil && !IsNil(o.Profiles) {
		return true
	}

	return false
}

// SetProfiles gets a reference to the given []SocialProfileReq and assigns it to the Profiles field.
func (o *MultiFieldReqWithOptions) SetProfiles(v []SocialProfileReq) {
	o.Profiles = v
}

// GetMaids returns the Maids field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetMaids() []string {
	if o == nil || IsNil(o.Maids) {
		var ret []string
		return ret
	}
	return o.Maids
}

// GetMaidsOk returns a tuple with the Maids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetMaidsOk() ([]string, bool) {
	if o == nil || IsNil(o.Maids) {
		return nil, false
	}
	return o.Maids, true
}

// HasMaids returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasMaids() bool {
	if o != nil && !IsNil(o.Maids) {
		return true
	}

	return false
}

// SetMaids gets a reference to the given []string and assigns it to the Maids field.
func (o *MultiFieldReqWithOptions) SetMaids(v []string) {
	o.Maids = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetName() PersonNameReq {
	if o == nil || IsNil(o.Name) {
		var ret PersonNameReq
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetNameOk() (*PersonNameReq, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given PersonNameReq and assigns it to the Name field.
func (o *MultiFieldReqWithOptions) SetName(v PersonNameReq) {
	o.Name = &v
}

// GetPartnerKeys returns the PartnerKeys field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetPartnerKeys() map[string]string {
	if o == nil || IsNil(o.PartnerKeys) {
		var ret map[string]string
		return ret
	}
	return *o.PartnerKeys
}

// GetPartnerKeysOk returns a tuple with the PartnerKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetPartnerKeysOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.PartnerKeys) {
		return nil, false
	}
	return o.PartnerKeys, true
}

// HasPartnerKeys returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasPartnerKeys() bool {
	if o != nil && !IsNil(o.PartnerKeys) {
		return true
	}

	return false
}

// SetPartnerKeys gets a reference to the given map[string]string and assigns it to the PartnerKeys field.
func (o *MultiFieldReqWithOptions) SetPartnerKeys(v map[string]string) {
	o.PartnerKeys = &v
}

// GetLiNonid returns the LiNonid field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetLiNonid() string {
	if o == nil || IsNil(o.LiNonid) {
		var ret string
		return ret
	}
	return *o.LiNonid
}

// GetLiNonidOk returns a tuple with the LiNonid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetLiNonidOk() (*string, bool) {
	if o == nil || IsNil(o.LiNonid) {
		return nil, false
	}
	return o.LiNonid, true
}

// HasLiNonid returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasLiNonid() bool {
	if o != nil && !IsNil(o.LiNonid) {
		return true
	}

	return false
}

// SetLiNonid gets a reference to the given string and assigns it to the LiNonid field.
func (o *MultiFieldReqWithOptions) SetLiNonid(v string) {
	o.LiNonid = &v
}

// GetPanoramaId returns the PanoramaId field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetPanoramaId() string {
	if o == nil || IsNil(o.PanoramaId) {
		var ret string
		return ret
	}
	return *o.PanoramaId
}

// GetPanoramaIdOk returns a tuple with the PanoramaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetPanoramaIdOk() (*string, bool) {
	if o == nil || IsNil(o.PanoramaId) {
		return nil, false
	}
	return o.PanoramaId, true
}

// HasPanoramaId returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasPanoramaId() bool {
	if o != nil && !IsNil(o.PanoramaId) {
		return true
	}

	return false
}

// SetPanoramaId gets a reference to the given string and assigns it to the PanoramaId field.
func (o *MultiFieldReqWithOptions) SetPanoramaId(v string) {
	o.PanoramaId = &v
}

// GetPlacekey returns the Placekey field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetPlacekey() string {
	if o == nil || IsNil(o.Placekey) {
		var ret string
		return ret
	}
	return *o.Placekey
}

// GetPlacekeyOk returns a tuple with the Placekey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetPlacekeyOk() (*string, bool) {
	if o == nil || IsNil(o.Placekey) {
		return nil, false
	}
	return o.Placekey, true
}

// HasPlacekey returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasPlacekey() bool {
	if o != nil && !IsNil(o.Placekey) {
		return true
	}

	return false
}

// SetPlacekey gets a reference to the given string and assigns it to the Placekey field.
func (o *MultiFieldReqWithOptions) SetPlacekey(v string) {
	o.Placekey = &v
}

// GetGeneratePid returns the GeneratePid field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetGeneratePid() bool {
	if o == nil || IsNil(o.GeneratePid) {
		var ret bool
		return ret
	}
	return *o.GeneratePid
}

// GetGeneratePidOk returns a tuple with the GeneratePid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetGeneratePidOk() (*bool, bool) {
	if o == nil || IsNil(o.GeneratePid) {
		return nil, false
	}
	return o.GeneratePid, true
}

// HasGeneratePid returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasGeneratePid() bool {
	if o != nil && !IsNil(o.GeneratePid) {
		return true
	}

	return false
}

// SetGeneratePid gets a reference to the given bool and assigns it to the GeneratePid field.
func (o *MultiFieldReqWithOptions) SetGeneratePid(v bool) {
	o.GeneratePid = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *MultiFieldReqWithOptions) SetEmail(v string) {
	o.Email = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *MultiFieldReqWithOptions) SetPhone(v string) {
	o.Phone = &v
}

// GetProfile returns the Profile field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetProfile() SocialProfileReq {
	if o == nil || IsNil(o.Profile) {
		var ret SocialProfileReq
		return ret
	}
	return *o.Profile
}

// GetProfileOk returns a tuple with the Profile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetProfileOk() (*SocialProfileReq, bool) {
	if o == nil || IsNil(o.Profile) {
		return nil, false
	}
	return o.Profile, true
}

// HasProfile returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasProfile() bool {
	if o != nil && !IsNil(o.Profile) {
		return true
	}

	return false
}

// SetProfile gets a reference to the given SocialProfileReq and assigns it to the Profile field.
func (o *MultiFieldReqWithOptions) SetProfile(v SocialProfileReq) {
	o.Profile = &v
}

// GetMaid returns the Maid field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetMaid() string {
	if o == nil || IsNil(o.Maid) {
		var ret string
		return ret
	}
	return *o.Maid
}

// GetMaidOk returns a tuple with the Maid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetMaidOk() (*string, bool) {
	if o == nil || IsNil(o.Maid) {
		return nil, false
	}
	return o.Maid, true
}

// HasMaid returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasMaid() bool {
	if o != nil && !IsNil(o.Maid) {
		return true
	}

	return false
}

// SetMaid gets a reference to the given string and assigns it to the Maid field.
func (o *MultiFieldReqWithOptions) SetMaid(v string) {
	o.Maid = &v
}

// GetInfer returns the Infer field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetInfer() bool {
	if o == nil || IsNil(o.Infer) {
		var ret bool
		return ret
	}
	return *o.Infer
}

// GetInferOk returns a tuple with the Infer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetInferOk() (*bool, bool) {
	if o == nil || IsNil(o.Infer) {
		return nil, false
	}
	return o.Infer, true
}

// HasInfer returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasInfer() bool {
	if o != nil && !IsNil(o.Infer) {
		return true
	}

	return false
}

// SetInfer gets a reference to the given bool and assigns it to the Infer field.
func (o *MultiFieldReqWithOptions) SetInfer(v bool) {
	o.Infer = &v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetConfidence() string {
	if o == nil || IsNil(o.Confidence) {
		var ret string
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetConfidenceOk() (*string, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given string and assigns it to the Confidence field.
func (o *MultiFieldReqWithOptions) SetConfidence(v string) {
	o.Confidence = &v
}

// GetBirthday returns the Birthday field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetBirthday() string {
	if o == nil || IsNil(o.Birthday) {
		var ret string
		return ret
	}
	return *o.Birthday
}

// GetBirthdayOk returns a tuple with the Birthday field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetBirthdayOk() (*string, bool) {
	if o == nil || IsNil(o.Birthday) {
		return nil, false
	}
	return o.Birthday, true
}

// HasBirthday returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasBirthday() bool {
	if o != nil && !IsNil(o.Birthday) {
		return true
	}

	return false
}

// SetBirthday gets a reference to the given string and assigns it to the Birthday field.
func (o *MultiFieldReqWithOptions) SetBirthday(v string) {
	o.Birthday = &v
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress) {
		var ret string
		return ret
	}
	return *o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetIpAddressOk() (*string, bool) {
	if o == nil || IsNil(o.IpAddress) {
		return nil, false
	}
	return o.IpAddress, true
}

// HasIpAddress returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasIpAddress() bool {
	if o != nil && !IsNil(o.IpAddress) {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given string and assigns it to the IpAddress field.
func (o *MultiFieldReqWithOptions) SetIpAddress(v string) {
	o.IpAddress = &v
}

// GetCountries returns the Countries field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetCountries() []string {
	if o == nil || IsNil(o.Countries) {
		var ret []string
		return ret
	}
	return o.Countries
}

// GetCountriesOk returns a tuple with the Countries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetCountriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Countries) {
		return nil, false
	}
	return o.Countries, true
}

// HasCountries returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasCountries() bool {
	if o != nil && !IsNil(o.Countries) {
		return true
	}

	return false
}

// SetCountries gets a reference to the given []string and assigns it to the Countries field.
func (o *MultiFieldReqWithOptions) SetCountries(v []string) {
	o.Countries = v
}

// GetExcludeCountries returns the ExcludeCountries field value if set, zero value otherwise.
func (o *MultiFieldReqWithOptions) GetExcludeCountries() []string {
	if o == nil || IsNil(o.ExcludeCountries) {
		var ret []string
		return ret
	}
	return o.ExcludeCountries
}

// GetExcludeCountriesOk returns a tuple with the ExcludeCountries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiFieldReqWithOptions) GetExcludeCountriesOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeCountries) {
		return nil, false
	}
	return o.ExcludeCountries, true
}

// HasExcludeCountries returns a boolean if a field has been set.
func (o *MultiFieldReqWithOptions) HasExcludeCountries() bool {
	if o != nil && !IsNil(o.ExcludeCountries) {
		return true
	}

	return false
}

// SetExcludeCountries gets a reference to the given []string and assigns it to the ExcludeCountries field.
func (o *MultiFieldReqWithOptions) SetExcludeCountries(v []string) {
	o.ExcludeCountries = v
}

func (o MultiFieldReqWithOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultiFieldReqWithOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Twitter) {
		toSerialize["twitter"] = o.Twitter
	}
	if !IsNil(o.Linkedin) {
		toSerialize["linkedin"] = o.Linkedin
	}
	if !IsNil(o.RecordId) {
		toSerialize["recordId"] = o.RecordId
	}
	if !IsNil(o.PersonId) {
		toSerialize["personId"] = o.PersonId
	}
	if !IsNil(o.PartnerId) {
		toSerialize["partnerId"] = o.PartnerId
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Avatar) {
		toSerialize["avatar"] = o.Avatar
	}
	if !IsNil(o.Website) {
		toSerialize["website"] = o.Website
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !IsNil(o.Emails) {
		toSerialize["emails"] = o.Emails
	}
	if !IsNil(o.Phones) {
		toSerialize["phones"] = o.Phones
	}
	if !IsNil(o.Profiles) {
		toSerialize["profiles"] = o.Profiles
	}
	if !IsNil(o.Maids) {
		toSerialize["maids"] = o.Maids
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PartnerKeys) {
		toSerialize["partnerKeys"] = o.PartnerKeys
	}
	if !IsNil(o.LiNonid) {
		toSerialize["li_nonid"] = o.LiNonid
	}
	if !IsNil(o.PanoramaId) {
		toSerialize["panoramaId"] = o.PanoramaId
	}
	if !IsNil(o.Placekey) {
		toSerialize["placekey"] = o.Placekey
	}
	if !IsNil(o.GeneratePid) {
		toSerialize["generatePid"] = o.GeneratePid
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Profile) {
		toSerialize["profile"] = o.Profile
	}
	if !IsNil(o.Maid) {
		toSerialize["maid"] = o.Maid
	}
	if !IsNil(o.Infer) {
		toSerialize["infer"] = o.Infer
	}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.Birthday) {
		toSerialize["birthday"] = o.Birthday
	}
	if !IsNil(o.IpAddress) {
		toSerialize["ipAddress"] = o.IpAddress
	}
	if !IsNil(o.Countries) {
		toSerialize["countries"] = o.Countries
	}
	if !IsNil(o.ExcludeCountries) {
		toSerialize["excludeCountries"] = o.ExcludeCountries
	}
	return toSerialize, nil
}

type NullableMultiFieldReqWithOptions struct {
	value *MultiFieldReqWithOptions
	isSet bool
}

func (v NullableMultiFieldReqWithOptions) Get() *MultiFieldReqWithOptions {
	return v.value
}

func (v *NullableMultiFieldReqWithOptions) Set(val *MultiFieldReqWithOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableMultiFieldReqWithOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableMultiFieldReqWithOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultiFieldReqWithOptions(val *MultiFieldReqWithOptions) *NullableMultiFieldReqWithOptions {
	return &NullableMultiFieldReqWithOptions{value: val, isSet: true}
}

func (v NullableMultiFieldReqWithOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultiFieldReqWithOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


