/*
Fideo API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.4
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
)

// checks if the SignalsResponseV20240424 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignalsResponseV20240424{}

// SignalsResponseV20240424 struct for SignalsResponseV20240424
type SignalsResponseV20240424 struct {
	Name *NameWithAlias `json:"name,omitempty"`
	Demographics *Demographics `json:"demographics,omitempty"`
	Locations []Location `json:"locations,omitempty"`
	Emails []Email `json:"emails,omitempty"`
	Phones []Phone `json:"phones,omitempty"`
	PersonIds []string `json:"personIds,omitempty"`
	IpAddresses []IpAddress `json:"ipAddresses,omitempty"`
	Message *string `json:"message,omitempty"`
	SocialProfiles []SocialProfileDetails `json:"socialProfiles,omitempty"`
	Employment []Employment `json:"employment,omitempty"`
	Education []Education `json:"education,omitempty"`
	Photos []Photo `json:"photos,omitempty"`
	Economic *Economic `json:"economic,omitempty"`
}

// NewSignalsResponseV20240424 instantiates a new SignalsResponseV20240424 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignalsResponseV20240424() *SignalsResponseV20240424 {
	this := SignalsResponseV20240424{}
	return &this
}

// NewSignalsResponseV20240424WithDefaults instantiates a new SignalsResponseV20240424 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignalsResponseV20240424WithDefaults() *SignalsResponseV20240424 {
	this := SignalsResponseV20240424{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SignalsResponseV20240424) GetName() NameWithAlias {
	if o == nil || IsNil(o.Name) {
		var ret NameWithAlias
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalsResponseV20240424) GetNameOk() (*NameWithAlias, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SignalsResponseV20240424) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given NameWithAlias and assigns it to the Name field.
func (o *SignalsResponseV20240424) SetName(v NameWithAlias) {
	o.Name = &v
}

// GetDemographics returns the Demographics field value if set, zero value otherwise.
func (o *SignalsResponseV20240424) GetDemographics() Demographics {
	if o == nil || IsNil(o.Demographics) {
		var ret Demographics
		return ret
	}
	return *o.Demographics
}

// GetDemographicsOk returns a tuple with the Demographics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalsResponseV20240424) GetDemographicsOk() (*Demographics, bool) {
	if o == nil || IsNil(o.Demographics) {
		return nil, false
	}
	return o.Demographics, true
}

// HasDemographics returns a boolean if a field has been set.
func (o *SignalsResponseV20240424) HasDemographics() bool {
	if o != nil && !IsNil(o.Demographics) {
		return true
	}

	return false
}

// SetDemographics gets a reference to the given Demographics and assigns it to the Demographics field.
func (o *SignalsResponseV20240424) SetDemographics(v Demographics) {
	o.Demographics = &v
}

// GetLocations returns the Locations field value if set, zero value otherwise.
func (o *SignalsResponseV20240424) GetLocations() []Location {
	if o == nil || IsNil(o.Locations) {
		var ret []Location
		return ret
	}
	return o.Locations
}

// GetLocationsOk returns a tuple with the Locations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalsResponseV20240424) GetLocationsOk() ([]Location, bool) {
	if o == nil || IsNil(o.Locations) {
		return nil, false
	}
	return o.Locations, true
}

// HasLocations returns a boolean if a field has been set.
func (o *SignalsResponseV20240424) HasLocations() bool {
	if o != nil && !IsNil(o.Locations) {
		return true
	}

	return false
}

// SetLocations gets a reference to the given []Location and assigns it to the Locations field.
func (o *SignalsResponseV20240424) SetLocations(v []Location) {
	o.Locations = v
}

// GetEmails returns the Emails field value if set, zero value otherwise.
func (o *SignalsResponseV20240424) GetEmails() []Email {
	if o == nil || IsNil(o.Emails) {
		var ret []Email
		return ret
	}
	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalsResponseV20240424) GetEmailsOk() ([]Email, bool) {
	if o == nil || IsNil(o.Emails) {
		return nil, false
	}
	return o.Emails, true
}

// HasEmails returns a boolean if a field has been set.
func (o *SignalsResponseV20240424) HasEmails() bool {
	if o != nil && !IsNil(o.Emails) {
		return true
	}

	return false
}

// SetEmails gets a reference to the given []Email and assigns it to the Emails field.
func (o *SignalsResponseV20240424) SetEmails(v []Email) {
	o.Emails = v
}

// GetPhones returns the Phones field value if set, zero value otherwise.
func (o *SignalsResponseV20240424) GetPhones() []Phone {
	if o == nil || IsNil(o.Phones) {
		var ret []Phone
		return ret
	}
	return o.Phones
}

// GetPhonesOk returns a tuple with the Phones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalsResponseV20240424) GetPhonesOk() ([]Phone, bool) {
	if o == nil || IsNil(o.Phones) {
		return nil, false
	}
	return o.Phones, true
}

// HasPhones returns a boolean if a field has been set.
func (o *SignalsResponseV20240424) HasPhones() bool {
	if o != nil && !IsNil(o.Phones) {
		return true
	}

	return false
}

// SetPhones gets a reference to the given []Phone and assigns it to the Phones field.
func (o *SignalsResponseV20240424) SetPhones(v []Phone) {
	o.Phones = v
}

// GetPersonIds returns the PersonIds field value if set, zero value otherwise.
func (o *SignalsResponseV20240424) GetPersonIds() []string {
	if o == nil || IsNil(o.PersonIds) {
		var ret []string
		return ret
	}
	return o.PersonIds
}

// GetPersonIdsOk returns a tuple with the PersonIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalsResponseV20240424) GetPersonIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.PersonIds) {
		return nil, false
	}
	return o.PersonIds, true
}

// HasPersonIds returns a boolean if a field has been set.
func (o *SignalsResponseV20240424) HasPersonIds() bool {
	if o != nil && !IsNil(o.PersonIds) {
		return true
	}

	return false
}

// SetPersonIds gets a reference to the given []string and assigns it to the PersonIds field.
func (o *SignalsResponseV20240424) SetPersonIds(v []string) {
	o.PersonIds = v
}

// GetIpAddresses returns the IpAddresses field value if set, zero value otherwise.
func (o *SignalsResponseV20240424) GetIpAddresses() []IpAddress {
	if o == nil || IsNil(o.IpAddresses) {
		var ret []IpAddress
		return ret
	}
	return o.IpAddresses
}

// GetIpAddressesOk returns a tuple with the IpAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalsResponseV20240424) GetIpAddressesOk() ([]IpAddress, bool) {
	if o == nil || IsNil(o.IpAddresses) {
		return nil, false
	}
	return o.IpAddresses, true
}

// HasIpAddresses returns a boolean if a field has been set.
func (o *SignalsResponseV20240424) HasIpAddresses() bool {
	if o != nil && !IsNil(o.IpAddresses) {
		return true
	}

	return false
}

// SetIpAddresses gets a reference to the given []IpAddress and assigns it to the IpAddresses field.
func (o *SignalsResponseV20240424) SetIpAddresses(v []IpAddress) {
	o.IpAddresses = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SignalsResponseV20240424) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalsResponseV20240424) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SignalsResponseV20240424) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SignalsResponseV20240424) SetMessage(v string) {
	o.Message = &v
}

// GetSocialProfiles returns the SocialProfiles field value if set, zero value otherwise.
func (o *SignalsResponseV20240424) GetSocialProfiles() []SocialProfileDetails {
	if o == nil || IsNil(o.SocialProfiles) {
		var ret []SocialProfileDetails
		return ret
	}
	return o.SocialProfiles
}

// GetSocialProfilesOk returns a tuple with the SocialProfiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalsResponseV20240424) GetSocialProfilesOk() ([]SocialProfileDetails, bool) {
	if o == nil || IsNil(o.SocialProfiles) {
		return nil, false
	}
	return o.SocialProfiles, true
}

// HasSocialProfiles returns a boolean if a field has been set.
func (o *SignalsResponseV20240424) HasSocialProfiles() bool {
	if o != nil && !IsNil(o.SocialProfiles) {
		return true
	}

	return false
}

// SetSocialProfiles gets a reference to the given []SocialProfileDetails and assigns it to the SocialProfiles field.
func (o *SignalsResponseV20240424) SetSocialProfiles(v []SocialProfileDetails) {
	o.SocialProfiles = v
}

// GetEmployment returns the Employment field value if set, zero value otherwise.
func (o *SignalsResponseV20240424) GetEmployment() []Employment {
	if o == nil || IsNil(o.Employment) {
		var ret []Employment
		return ret
	}
	return o.Employment
}

// GetEmploymentOk returns a tuple with the Employment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalsResponseV20240424) GetEmploymentOk() ([]Employment, bool) {
	if o == nil || IsNil(o.Employment) {
		return nil, false
	}
	return o.Employment, true
}

// HasEmployment returns a boolean if a field has been set.
func (o *SignalsResponseV20240424) HasEmployment() bool {
	if o != nil && !IsNil(o.Employment) {
		return true
	}

	return false
}

// SetEmployment gets a reference to the given []Employment and assigns it to the Employment field.
func (o *SignalsResponseV20240424) SetEmployment(v []Employment) {
	o.Employment = v
}

// GetEducation returns the Education field value if set, zero value otherwise.
func (o *SignalsResponseV20240424) GetEducation() []Education {
	if o == nil || IsNil(o.Education) {
		var ret []Education
		return ret
	}
	return o.Education
}

// GetEducationOk returns a tuple with the Education field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalsResponseV20240424) GetEducationOk() ([]Education, bool) {
	if o == nil || IsNil(o.Education) {
		return nil, false
	}
	return o.Education, true
}

// HasEducation returns a boolean if a field has been set.
func (o *SignalsResponseV20240424) HasEducation() bool {
	if o != nil && !IsNil(o.Education) {
		return true
	}

	return false
}

// SetEducation gets a reference to the given []Education and assigns it to the Education field.
func (o *SignalsResponseV20240424) SetEducation(v []Education) {
	o.Education = v
}

// GetPhotos returns the Photos field value if set, zero value otherwise.
func (o *SignalsResponseV20240424) GetPhotos() []Photo {
	if o == nil || IsNil(o.Photos) {
		var ret []Photo
		return ret
	}
	return o.Photos
}

// GetPhotosOk returns a tuple with the Photos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalsResponseV20240424) GetPhotosOk() ([]Photo, bool) {
	if o == nil || IsNil(o.Photos) {
		return nil, false
	}
	return o.Photos, true
}

// HasPhotos returns a boolean if a field has been set.
func (o *SignalsResponseV20240424) HasPhotos() bool {
	if o != nil && !IsNil(o.Photos) {
		return true
	}

	return false
}

// SetPhotos gets a reference to the given []Photo and assigns it to the Photos field.
func (o *SignalsResponseV20240424) SetPhotos(v []Photo) {
	o.Photos = v
}

// GetEconomic returns the Economic field value if set, zero value otherwise.
func (o *SignalsResponseV20240424) GetEconomic() Economic {
	if o == nil || IsNil(o.Economic) {
		var ret Economic
		return ret
	}
	return *o.Economic
}

// GetEconomicOk returns a tuple with the Economic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalsResponseV20240424) GetEconomicOk() (*Economic, bool) {
	if o == nil || IsNil(o.Economic) {
		return nil, false
	}
	return o.Economic, true
}

// HasEconomic returns a boolean if a field has been set.
func (o *SignalsResponseV20240424) HasEconomic() bool {
	if o != nil && !IsNil(o.Economic) {
		return true
	}

	return false
}

// SetEconomic gets a reference to the given Economic and assigns it to the Economic field.
func (o *SignalsResponseV20240424) SetEconomic(v Economic) {
	o.Economic = &v
}

func (o SignalsResponseV20240424) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignalsResponseV20240424) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Demographics) {
		toSerialize["demographics"] = o.Demographics
	}
	if !IsNil(o.Locations) {
		toSerialize["locations"] = o.Locations
	}
	if !IsNil(o.Emails) {
		toSerialize["emails"] = o.Emails
	}
	if !IsNil(o.Phones) {
		toSerialize["phones"] = o.Phones
	}
	if !IsNil(o.PersonIds) {
		toSerialize["personIds"] = o.PersonIds
	}
	if !IsNil(o.IpAddresses) {
		toSerialize["ipAddresses"] = o.IpAddresses
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.SocialProfiles) {
		toSerialize["socialProfiles"] = o.SocialProfiles
	}
	if !IsNil(o.Employment) {
		toSerialize["employment"] = o.Employment
	}
	if !IsNil(o.Education) {
		toSerialize["education"] = o.Education
	}
	if !IsNil(o.Photos) {
		toSerialize["photos"] = o.Photos
	}
	if !IsNil(o.Economic) {
		toSerialize["economic"] = o.Economic
	}
	return toSerialize, nil
}

type NullableSignalsResponseV20240424 struct {
	value *SignalsResponseV20240424
	isSet bool
}

func (v NullableSignalsResponseV20240424) Get() *SignalsResponseV20240424 {
	return v.value
}

func (v *NullableSignalsResponseV20240424) Set(val *SignalsResponseV20240424) {
	v.value = val
	v.isSet = true
}

func (v NullableSignalsResponseV20240424) IsSet() bool {
	return v.isSet
}

func (v *NullableSignalsResponseV20240424) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignalsResponseV20240424(val *SignalsResponseV20240424) *NullableSignalsResponseV20240424 {
	return &NullableSignalsResponseV20240424{value: val, isSet: true}
}

func (v NullableSignalsResponseV20240424) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignalsResponseV20240424) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


