/*
Fideo API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.4
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PrefillResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrefillResponse{}

// PrefillResponse struct for PrefillResponse
type PrefillResponse struct {
	// UUIDv7 session identifier to send with reviewed identity data.
	SessionId string `json:"sessionId"`
	Status string `json:"status"`
	// Resolved identity in the same multifield shape accepted by the follow-up Prefill request. The caller may review or edit these values and resubmit them with the returned sessionId.
	Individual *MultiFieldReqWithOptions `json:"individual,omitempty"`
	Evaluation *PrefillEvaluation `json:"evaluation,omitempty"`
}

type _PrefillResponse PrefillResponse

// NewPrefillResponse instantiates a new PrefillResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrefillResponse(sessionId string, status string) *PrefillResponse {
	this := PrefillResponse{}
	this.SessionId = sessionId
	this.Status = status
	return &this
}

// NewPrefillResponseWithDefaults instantiates a new PrefillResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrefillResponseWithDefaults() *PrefillResponse {
	this := PrefillResponse{}
	return &this
}

// GetSessionId returns the SessionId field value
func (o *PrefillResponse) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *PrefillResponse) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *PrefillResponse) SetSessionId(v string) {
	o.SessionId = v
}

// GetStatus returns the Status field value
func (o *PrefillResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PrefillResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PrefillResponse) SetStatus(v string) {
	o.Status = v
}

// GetIndividual returns the Individual field value if set, zero value otherwise.
func (o *PrefillResponse) GetIndividual() MultiFieldReqWithOptions {
	if o == nil || IsNil(o.Individual) {
		var ret MultiFieldReqWithOptions
		return ret
	}
	return *o.Individual
}

// GetIndividualOk returns a tuple with the Individual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefillResponse) GetIndividualOk() (*MultiFieldReqWithOptions, bool) {
	if o == nil || IsNil(o.Individual) {
		return nil, false
	}
	return o.Individual, true
}

// HasIndividual returns a boolean if a field has been set.
func (o *PrefillResponse) HasIndividual() bool {
	if o != nil && !IsNil(o.Individual) {
		return true
	}

	return false
}

// SetIndividual gets a reference to the given MultiFieldReqWithOptions and assigns it to the Individual field.
func (o *PrefillResponse) SetIndividual(v MultiFieldReqWithOptions) {
	o.Individual = &v
}

// GetEvaluation returns the Evaluation field value if set, zero value otherwise.
func (o *PrefillResponse) GetEvaluation() PrefillEvaluation {
	if o == nil || IsNil(o.Evaluation) {
		var ret PrefillEvaluation
		return ret
	}
	return *o.Evaluation
}

// GetEvaluationOk returns a tuple with the Evaluation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefillResponse) GetEvaluationOk() (*PrefillEvaluation, bool) {
	if o == nil || IsNil(o.Evaluation) {
		return nil, false
	}
	return o.Evaluation, true
}

// HasEvaluation returns a boolean if a field has been set.
func (o *PrefillResponse) HasEvaluation() bool {
	if o != nil && !IsNil(o.Evaluation) {
		return true
	}

	return false
}

// SetEvaluation gets a reference to the given PrefillEvaluation and assigns it to the Evaluation field.
func (o *PrefillResponse) SetEvaluation(v PrefillEvaluation) {
	o.Evaluation = &v
}

func (o PrefillResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrefillResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sessionId"] = o.SessionId
	toSerialize["status"] = o.Status
	if !IsNil(o.Individual) {
		toSerialize["individual"] = o.Individual
	}
	if !IsNil(o.Evaluation) {
		toSerialize["evaluation"] = o.Evaluation
	}
	return toSerialize, nil
}

func (o *PrefillResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sessionId",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrefillResponse := _PrefillResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPrefillResponse)

	if err != nil {
		return err
	}

	*o = PrefillResponse(varPrefillResponse)

	return err
}

type NullablePrefillResponse struct {
	value *PrefillResponse
	isSet bool
}

func (v NullablePrefillResponse) Get() *PrefillResponse {
	return v.value
}

func (v *NullablePrefillResponse) Set(val *PrefillResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePrefillResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePrefillResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrefillResponse(val *PrefillResponse) *NullablePrefillResponse {
	return &NullablePrefillResponse{value: val, isSet: true}
}

func (v NullablePrefillResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrefillResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


