/*
Fideo API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.2
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SocialProfileReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SocialProfileReq{}

// SocialProfileReq struct for SocialProfileReq
type SocialProfileReq struct {
	Username *string `json:"username,omitempty"`
	Userid *string `json:"userid,omitempty"`
	Url *string `json:"url,omitempty"`
	Bio *string `json:"bio,omitempty"`
	Service *string `json:"service,omitempty"`
	Followers *int32 `json:"followers,omitempty"`
	Following *int32 `json:"following,omitempty"`
	Score *int32 `json:"score,omitempty"`
}

// NewSocialProfileReq instantiates a new SocialProfileReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSocialProfileReq() *SocialProfileReq {
	this := SocialProfileReq{}
	return &this
}

// NewSocialProfileReqWithDefaults instantiates a new SocialProfileReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSocialProfileReqWithDefaults() *SocialProfileReq {
	this := SocialProfileReq{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *SocialProfileReq) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialProfileReq) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *SocialProfileReq) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *SocialProfileReq) SetUsername(v string) {
	o.Username = &v
}

// GetUserid returns the Userid field value if set, zero value otherwise.
func (o *SocialProfileReq) GetUserid() string {
	if o == nil || IsNil(o.Userid) {
		var ret string
		return ret
	}
	return *o.Userid
}

// GetUseridOk returns a tuple with the Userid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialProfileReq) GetUseridOk() (*string, bool) {
	if o == nil || IsNil(o.Userid) {
		return nil, false
	}
	return o.Userid, true
}

// HasUserid returns a boolean if a field has been set.
func (o *SocialProfileReq) HasUserid() bool {
	if o != nil && !IsNil(o.Userid) {
		return true
	}

	return false
}

// SetUserid gets a reference to the given string and assigns it to the Userid field.
func (o *SocialProfileReq) SetUserid(v string) {
	o.Userid = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *SocialProfileReq) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialProfileReq) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *SocialProfileReq) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *SocialProfileReq) SetUrl(v string) {
	o.Url = &v
}

// GetBio returns the Bio field value if set, zero value otherwise.
func (o *SocialProfileReq) GetBio() string {
	if o == nil || IsNil(o.Bio) {
		var ret string
		return ret
	}
	return *o.Bio
}

// GetBioOk returns a tuple with the Bio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialProfileReq) GetBioOk() (*string, bool) {
	if o == nil || IsNil(o.Bio) {
		return nil, false
	}
	return o.Bio, true
}

// HasBio returns a boolean if a field has been set.
func (o *SocialProfileReq) HasBio() bool {
	if o != nil && !IsNil(o.Bio) {
		return true
	}

	return false
}

// SetBio gets a reference to the given string and assigns it to the Bio field.
func (o *SocialProfileReq) SetBio(v string) {
	o.Bio = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *SocialProfileReq) GetService() string {
	if o == nil || IsNil(o.Service) {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialProfileReq) GetServiceOk() (*string, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *SocialProfileReq) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *SocialProfileReq) SetService(v string) {
	o.Service = &v
}

// GetFollowers returns the Followers field value if set, zero value otherwise.
func (o *SocialProfileReq) GetFollowers() int32 {
	if o == nil || IsNil(o.Followers) {
		var ret int32
		return ret
	}
	return *o.Followers
}

// GetFollowersOk returns a tuple with the Followers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialProfileReq) GetFollowersOk() (*int32, bool) {
	if o == nil || IsNil(o.Followers) {
		return nil, false
	}
	return o.Followers, true
}

// HasFollowers returns a boolean if a field has been set.
func (o *SocialProfileReq) HasFollowers() bool {
	if o != nil && !IsNil(o.Followers) {
		return true
	}

	return false
}

// SetFollowers gets a reference to the given int32 and assigns it to the Followers field.
func (o *SocialProfileReq) SetFollowers(v int32) {
	o.Followers = &v
}

// GetFollowing returns the Following field value if set, zero value otherwise.
func (o *SocialProfileReq) GetFollowing() int32 {
	if o == nil || IsNil(o.Following) {
		var ret int32
		return ret
	}
	return *o.Following
}

// GetFollowingOk returns a tuple with the Following field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialProfileReq) GetFollowingOk() (*int32, bool) {
	if o == nil || IsNil(o.Following) {
		return nil, false
	}
	return o.Following, true
}

// HasFollowing returns a boolean if a field has been set.
func (o *SocialProfileReq) HasFollowing() bool {
	if o != nil && !IsNil(o.Following) {
		return true
	}

	return false
}

// SetFollowing gets a reference to the given int32 and assigns it to the Following field.
func (o *SocialProfileReq) SetFollowing(v int32) {
	o.Following = &v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *SocialProfileReq) GetScore() int32 {
	if o == nil || IsNil(o.Score) {
		var ret int32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SocialProfileReq) GetScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *SocialProfileReq) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given int32 and assigns it to the Score field.
func (o *SocialProfileReq) SetScore(v int32) {
	o.Score = &v
}

func (o SocialProfileReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SocialProfileReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Userid) {
		toSerialize["userid"] = o.Userid
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Bio) {
		toSerialize["bio"] = o.Bio
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.Followers) {
		toSerialize["followers"] = o.Followers
	}
	if !IsNil(o.Following) {
		toSerialize["following"] = o.Following
	}
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	return toSerialize, nil
}

type NullableSocialProfileReq struct {
	value *SocialProfileReq
	isSet bool
}

func (v NullableSocialProfileReq) Get() *SocialProfileReq {
	return v.value
}

func (v *NullableSocialProfileReq) Set(val *SocialProfileReq) {
	v.value = val
	v.isSet = true
}

func (v NullableSocialProfileReq) IsSet() bool {
	return v.isSet
}

func (v *NullableSocialProfileReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSocialProfileReq(val *SocialProfileReq) *NullableSocialProfileReq {
	return &NullableSocialProfileReq{value: val, isSet: true}
}

func (v NullableSocialProfileReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSocialProfileReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


