/*
Fideo API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.4
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
)

// checks if the SignalPatternResponseUnitCount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignalPatternResponseUnitCount{}

// SignalPatternResponseUnitCount struct for SignalPatternResponseUnitCount
type SignalPatternResponseUnitCount struct {
	// Type of event
	Type *string `json:"type,omitempty"`
	// Number of observations
	Observations *int64 `json:"observations,omitempty"`
	// Number of sources
	Sources *int64 `json:"sources,omitempty"`
}

// NewSignalPatternResponseUnitCount instantiates a new SignalPatternResponseUnitCount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignalPatternResponseUnitCount() *SignalPatternResponseUnitCount {
	this := SignalPatternResponseUnitCount{}
	return &this
}

// NewSignalPatternResponseUnitCountWithDefaults instantiates a new SignalPatternResponseUnitCount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignalPatternResponseUnitCountWithDefaults() *SignalPatternResponseUnitCount {
	this := SignalPatternResponseUnitCount{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SignalPatternResponseUnitCount) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalPatternResponseUnitCount) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SignalPatternResponseUnitCount) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SignalPatternResponseUnitCount) SetType(v string) {
	o.Type = &v
}

// GetObservations returns the Observations field value if set, zero value otherwise.
func (o *SignalPatternResponseUnitCount) GetObservations() int64 {
	if o == nil || IsNil(o.Observations) {
		var ret int64
		return ret
	}
	return *o.Observations
}

// GetObservationsOk returns a tuple with the Observations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalPatternResponseUnitCount) GetObservationsOk() (*int64, bool) {
	if o == nil || IsNil(o.Observations) {
		return nil, false
	}
	return o.Observations, true
}

// HasObservations returns a boolean if a field has been set.
func (o *SignalPatternResponseUnitCount) HasObservations() bool {
	if o != nil && !IsNil(o.Observations) {
		return true
	}

	return false
}

// SetObservations gets a reference to the given int64 and assigns it to the Observations field.
func (o *SignalPatternResponseUnitCount) SetObservations(v int64) {
	o.Observations = &v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *SignalPatternResponseUnitCount) GetSources() int64 {
	if o == nil || IsNil(o.Sources) {
		var ret int64
		return ret
	}
	return *o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalPatternResponseUnitCount) GetSourcesOk() (*int64, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *SignalPatternResponseUnitCount) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given int64 and assigns it to the Sources field.
func (o *SignalPatternResponseUnitCount) SetSources(v int64) {
	o.Sources = &v
}

func (o SignalPatternResponseUnitCount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignalPatternResponseUnitCount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Observations) {
		toSerialize["observations"] = o.Observations
	}
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}
	return toSerialize, nil
}

type NullableSignalPatternResponseUnitCount struct {
	value *SignalPatternResponseUnitCount
	isSet bool
}

func (v NullableSignalPatternResponseUnitCount) Get() *SignalPatternResponseUnitCount {
	return v.value
}

func (v *NullableSignalPatternResponseUnitCount) Set(val *SignalPatternResponseUnitCount) {
	v.value = val
	v.isSet = true
}

func (v NullableSignalPatternResponseUnitCount) IsSet() bool {
	return v.isSet
}

func (v *NullableSignalPatternResponseUnitCount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignalPatternResponseUnitCount(val *SignalPatternResponseUnitCount) *NullableSignalPatternResponseUnitCount {
	return &NullableSignalPatternResponseUnitCount{value: val, isSet: true}
}

func (v NullableSignalPatternResponseUnitCount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignalPatternResponseUnitCount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


