/*
Fideo API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.4
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
)

// checks if the EducationDate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EducationDate{}

// EducationDate struct for EducationDate
type EducationDate struct {
	Year *int32 `json:"year,omitempty"`
	Month *int32 `json:"month,omitempty"`
	Day *int32 `json:"day,omitempty"`
}

// NewEducationDate instantiates a new EducationDate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEducationDate() *EducationDate {
	this := EducationDate{}
	return &this
}

// NewEducationDateWithDefaults instantiates a new EducationDate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEducationDateWithDefaults() *EducationDate {
	this := EducationDate{}
	return &this
}

// GetYear returns the Year field value if set, zero value otherwise.
func (o *EducationDate) GetYear() int32 {
	if o == nil || IsNil(o.Year) {
		var ret int32
		return ret
	}
	return *o.Year
}

// GetYearOk returns a tuple with the Year field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EducationDate) GetYearOk() (*int32, bool) {
	if o == nil || IsNil(o.Year) {
		return nil, false
	}
	return o.Year, true
}

// HasYear returns a boolean if a field has been set.
func (o *EducationDate) HasYear() bool {
	if o != nil && !IsNil(o.Year) {
		return true
	}

	return false
}

// SetYear gets a reference to the given int32 and assigns it to the Year field.
func (o *EducationDate) SetYear(v int32) {
	o.Year = &v
}

// GetMonth returns the Month field value if set, zero value otherwise.
func (o *EducationDate) GetMonth() int32 {
	if o == nil || IsNil(o.Month) {
		var ret int32
		return ret
	}
	return *o.Month
}

// GetMonthOk returns a tuple with the Month field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EducationDate) GetMonthOk() (*int32, bool) {
	if o == nil || IsNil(o.Month) {
		return nil, false
	}
	return o.Month, true
}

// HasMonth returns a boolean if a field has been set.
func (o *EducationDate) HasMonth() bool {
	if o != nil && !IsNil(o.Month) {
		return true
	}

	return false
}

// SetMonth gets a reference to the given int32 and assigns it to the Month field.
func (o *EducationDate) SetMonth(v int32) {
	o.Month = &v
}

// GetDay returns the Day field value if set, zero value otherwise.
func (o *EducationDate) GetDay() int32 {
	if o == nil || IsNil(o.Day) {
		var ret int32
		return ret
	}
	return *o.Day
}

// GetDayOk returns a tuple with the Day field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EducationDate) GetDayOk() (*int32, bool) {
	if o == nil || IsNil(o.Day) {
		return nil, false
	}
	return o.Day, true
}

// HasDay returns a boolean if a field has been set.
func (o *EducationDate) HasDay() bool {
	if o != nil && !IsNil(o.Day) {
		return true
	}

	return false
}

// SetDay gets a reference to the given int32 and assigns it to the Day field.
func (o *EducationDate) SetDay(v int32) {
	o.Day = &v
}

func (o EducationDate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EducationDate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Year) {
		toSerialize["year"] = o.Year
	}
	if !IsNil(o.Month) {
		toSerialize["month"] = o.Month
	}
	if !IsNil(o.Day) {
		toSerialize["day"] = o.Day
	}
	return toSerialize, nil
}

type NullableEducationDate struct {
	value *EducationDate
	isSet bool
}

func (v NullableEducationDate) Get() *EducationDate {
	return v.value
}

func (v *NullableEducationDate) Set(val *EducationDate) {
	v.value = val
	v.isSet = true
}

func (v NullableEducationDate) IsSet() bool {
	return v.isSet
}

func (v *NullableEducationDate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEducationDate(val *EducationDate) *NullableEducationDate {
	return &NullableEducationDate{value: val, isSet: true}
}

func (v NullableEducationDate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEducationDate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


