/*
Fideo API

This is a representation of the Fideo API based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). Some useful links: - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.0
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
)

// checks if the EmploymentDate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmploymentDate{}

// EmploymentDate struct for EmploymentDate
type EmploymentDate struct {
	Year *int32 `json:"year,omitempty"`
	Month *int32 `json:"month,omitempty"`
	Day *int32 `json:"day,omitempty"`
}

// NewEmploymentDate instantiates a new EmploymentDate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmploymentDate() *EmploymentDate {
	this := EmploymentDate{}
	return &this
}

// NewEmploymentDateWithDefaults instantiates a new EmploymentDate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmploymentDateWithDefaults() *EmploymentDate {
	this := EmploymentDate{}
	return &this
}

// GetYear returns the Year field value if set, zero value otherwise.
func (o *EmploymentDate) GetYear() int32 {
	if o == nil || IsNil(o.Year) {
		var ret int32
		return ret
	}
	return *o.Year
}

// GetYearOk returns a tuple with the Year field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmploymentDate) GetYearOk() (*int32, bool) {
	if o == nil || IsNil(o.Year) {
		return nil, false
	}
	return o.Year, true
}

// HasYear returns a boolean if a field has been set.
func (o *EmploymentDate) HasYear() bool {
	if o != nil && !IsNil(o.Year) {
		return true
	}

	return false
}

// SetYear gets a reference to the given int32 and assigns it to the Year field.
func (o *EmploymentDate) SetYear(v int32) {
	o.Year = &v
}

// GetMonth returns the Month field value if set, zero value otherwise.
func (o *EmploymentDate) GetMonth() int32 {
	if o == nil || IsNil(o.Month) {
		var ret int32
		return ret
	}
	return *o.Month
}

// GetMonthOk returns a tuple with the Month field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmploymentDate) GetMonthOk() (*int32, bool) {
	if o == nil || IsNil(o.Month) {
		return nil, false
	}
	return o.Month, true
}

// HasMonth returns a boolean if a field has been set.
func (o *EmploymentDate) HasMonth() bool {
	if o != nil && !IsNil(o.Month) {
		return true
	}

	return false
}

// SetMonth gets a reference to the given int32 and assigns it to the Month field.
func (o *EmploymentDate) SetMonth(v int32) {
	o.Month = &v
}

// GetDay returns the Day field value if set, zero value otherwise.
func (o *EmploymentDate) GetDay() int32 {
	if o == nil || IsNil(o.Day) {
		var ret int32
		return ret
	}
	return *o.Day
}

// GetDayOk returns a tuple with the Day field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmploymentDate) GetDayOk() (*int32, bool) {
	if o == nil || IsNil(o.Day) {
		return nil, false
	}
	return o.Day, true
}

// HasDay returns a boolean if a field has been set.
func (o *EmploymentDate) HasDay() bool {
	if o != nil && !IsNil(o.Day) {
		return true
	}

	return false
}

// SetDay gets a reference to the given int32 and assigns it to the Day field.
func (o *EmploymentDate) SetDay(v int32) {
	o.Day = &v
}

func (o EmploymentDate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmploymentDate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Year) {
		toSerialize["year"] = o.Year
	}
	if !IsNil(o.Month) {
		toSerialize["month"] = o.Month
	}
	if !IsNil(o.Day) {
		toSerialize["day"] = o.Day
	}
	return toSerialize, nil
}

type NullableEmploymentDate struct {
	value *EmploymentDate
	isSet bool
}

func (v NullableEmploymentDate) Get() *EmploymentDate {
	return v.value
}

func (v *NullableEmploymentDate) Set(val *EmploymentDate) {
	v.value = val
	v.isSet = true
}

func (v NullableEmploymentDate) IsSet() bool {
	return v.isSet
}

func (v *NullableEmploymentDate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmploymentDate(val *EmploymentDate) *NullableEmploymentDate {
	return &NullableEmploymentDate{value: val, isSet: true}
}

func (v NullableEmploymentDate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmploymentDate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


