/*
Fideo Production API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.4
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
)

// checks if the SignalPatternResponseUnit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignalPatternResponseUnit{}

// SignalPatternResponseUnit struct for SignalPatternResponseUnit
type SignalPatternResponseUnit struct {
	// Number of observations
	Observations *int64 `json:"observations,omitempty"`
	// Number of sources
	Sources *int64 `json:"sources,omitempty"`
	Events []SignalPatternResponseUnitCount `json:"events,omitempty"`
}

// NewSignalPatternResponseUnit instantiates a new SignalPatternResponseUnit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignalPatternResponseUnit() *SignalPatternResponseUnit {
	this := SignalPatternResponseUnit{}
	return &this
}

// NewSignalPatternResponseUnitWithDefaults instantiates a new SignalPatternResponseUnit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignalPatternResponseUnitWithDefaults() *SignalPatternResponseUnit {
	this := SignalPatternResponseUnit{}
	return &this
}

// GetObservations returns the Observations field value if set, zero value otherwise.
func (o *SignalPatternResponseUnit) GetObservations() int64 {
	if o == nil || IsNil(o.Observations) {
		var ret int64
		return ret
	}
	return *o.Observations
}

// GetObservationsOk returns a tuple with the Observations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalPatternResponseUnit) GetObservationsOk() (*int64, bool) {
	if o == nil || IsNil(o.Observations) {
		return nil, false
	}
	return o.Observations, true
}

// HasObservations returns a boolean if a field has been set.
func (o *SignalPatternResponseUnit) HasObservations() bool {
	if o != nil && !IsNil(o.Observations) {
		return true
	}

	return false
}

// SetObservations gets a reference to the given int64 and assigns it to the Observations field.
func (o *SignalPatternResponseUnit) SetObservations(v int64) {
	o.Observations = &v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *SignalPatternResponseUnit) GetSources() int64 {
	if o == nil || IsNil(o.Sources) {
		var ret int64
		return ret
	}
	return *o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalPatternResponseUnit) GetSourcesOk() (*int64, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *SignalPatternResponseUnit) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given int64 and assigns it to the Sources field.
func (o *SignalPatternResponseUnit) SetSources(v int64) {
	o.Sources = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *SignalPatternResponseUnit) GetEvents() []SignalPatternResponseUnitCount {
	if o == nil || IsNil(o.Events) {
		var ret []SignalPatternResponseUnitCount
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignalPatternResponseUnit) GetEventsOk() ([]SignalPatternResponseUnitCount, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *SignalPatternResponseUnit) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []SignalPatternResponseUnitCount and assigns it to the Events field.
func (o *SignalPatternResponseUnit) SetEvents(v []SignalPatternResponseUnitCount) {
	o.Events = v
}

func (o SignalPatternResponseUnit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignalPatternResponseUnit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Observations) {
		toSerialize["observations"] = o.Observations
	}
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	return toSerialize, nil
}

type NullableSignalPatternResponseUnit struct {
	value *SignalPatternResponseUnit
	isSet bool
}

func (v NullableSignalPatternResponseUnit) Get() *SignalPatternResponseUnit {
	return v.value
}

func (v *NullableSignalPatternResponseUnit) Set(val *SignalPatternResponseUnit) {
	v.value = val
	v.isSet = true
}

func (v NullableSignalPatternResponseUnit) IsSet() bool {
	return v.isSet
}

func (v *NullableSignalPatternResponseUnit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignalPatternResponseUnit(val *SignalPatternResponseUnit) *NullableSignalPatternResponseUnit {
	return &NullableSignalPatternResponseUnit{value: val, isSet: true}
}

func (v NullableSignalPatternResponseUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignalPatternResponseUnit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


