/*
Fideo API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.4
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
)

// checks if the LensGraphResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LensGraphResponse{}

// LensGraphResponse struct for LensGraphResponse
type LensGraphResponse struct {
	Graph []interface{} `json:"graph,omitempty"`
	SeedGraphIds *map[string][]string `json:"seed_graph_ids,omitempty"`
}

// NewLensGraphResponse instantiates a new LensGraphResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLensGraphResponse() *LensGraphResponse {
	this := LensGraphResponse{}
	return &this
}

// NewLensGraphResponseWithDefaults instantiates a new LensGraphResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLensGraphResponseWithDefaults() *LensGraphResponse {
	this := LensGraphResponse{}
	return &this
}

// GetGraph returns the Graph field value if set, zero value otherwise.
func (o *LensGraphResponse) GetGraph() []interface{} {
	if o == nil || IsNil(o.Graph) {
		var ret []interface{}
		return ret
	}
	return o.Graph
}

// GetGraphOk returns a tuple with the Graph field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LensGraphResponse) GetGraphOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Graph) {
		return nil, false
	}
	return o.Graph, true
}

// HasGraph returns a boolean if a field has been set.
func (o *LensGraphResponse) HasGraph() bool {
	if o != nil && !IsNil(o.Graph) {
		return true
	}

	return false
}

// SetGraph gets a reference to the given []interface{} and assigns it to the Graph field.
func (o *LensGraphResponse) SetGraph(v []interface{}) {
	o.Graph = v
}

// GetSeedGraphIds returns the SeedGraphIds field value if set, zero value otherwise.
func (o *LensGraphResponse) GetSeedGraphIds() map[string][]string {
	if o == nil || IsNil(o.SeedGraphIds) {
		var ret map[string][]string
		return ret
	}
	return *o.SeedGraphIds
}

// GetSeedGraphIdsOk returns a tuple with the SeedGraphIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LensGraphResponse) GetSeedGraphIdsOk() (*map[string][]string, bool) {
	if o == nil || IsNil(o.SeedGraphIds) {
		return nil, false
	}
	return o.SeedGraphIds, true
}

// HasSeedGraphIds returns a boolean if a field has been set.
func (o *LensGraphResponse) HasSeedGraphIds() bool {
	if o != nil && !IsNil(o.SeedGraphIds) {
		return true
	}

	return false
}

// SetSeedGraphIds gets a reference to the given map[string][]string and assigns it to the SeedGraphIds field.
func (o *LensGraphResponse) SetSeedGraphIds(v map[string][]string) {
	o.SeedGraphIds = &v
}

func (o LensGraphResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LensGraphResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Graph) {
		toSerialize["graph"] = o.Graph
	}
	if !IsNil(o.SeedGraphIds) {
		toSerialize["seed_graph_ids"] = o.SeedGraphIds
	}
	return toSerialize, nil
}

type NullableLensGraphResponse struct {
	value *LensGraphResponse
	isSet bool
}

func (v NullableLensGraphResponse) Get() *LensGraphResponse {
	return v.value
}

func (v *NullableLensGraphResponse) Set(val *LensGraphResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLensGraphResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLensGraphResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLensGraphResponse(val *LensGraphResponse) *NullableLensGraphResponse {
	return &NullableLensGraphResponse{value: val, isSet: true}
}

func (v NullableLensGraphResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLensGraphResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


