/*
Fideo API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.4
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LensGraphRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LensGraphRequest{}

// LensGraphRequest struct for LensGraphRequest
type LensGraphRequest struct {
	// Lens graph response mode.
	Mode string `json:"mode"`
	// Comma-separated Lens graph seed query.
	Query string `json:"query"`
	// Requested graph hop count. Defaults to 2 when omitted.
	Hops *int32 `json:"hops,omitempty"`
}

type _LensGraphRequest LensGraphRequest

// NewLensGraphRequest instantiates a new LensGraphRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLensGraphRequest(mode string, query string) *LensGraphRequest {
	this := LensGraphRequest{}
	this.Mode = mode
	this.Query = query
	var hops int32 = 2
	this.Hops = &hops
	return &this
}

// NewLensGraphRequestWithDefaults instantiates a new LensGraphRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLensGraphRequestWithDefaults() *LensGraphRequest {
	this := LensGraphRequest{}
	var hops int32 = 2
	this.Hops = &hops
	return &this
}

// GetMode returns the Mode field value
func (o *LensGraphRequest) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *LensGraphRequest) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *LensGraphRequest) SetMode(v string) {
	o.Mode = v
}

// GetQuery returns the Query field value
func (o *LensGraphRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *LensGraphRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *LensGraphRequest) SetQuery(v string) {
	o.Query = v
}

// GetHops returns the Hops field value if set, zero value otherwise.
func (o *LensGraphRequest) GetHops() int32 {
	if o == nil || IsNil(o.Hops) {
		var ret int32
		return ret
	}
	return *o.Hops
}

// GetHopsOk returns a tuple with the Hops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LensGraphRequest) GetHopsOk() (*int32, bool) {
	if o == nil || IsNil(o.Hops) {
		return nil, false
	}
	return o.Hops, true
}

// HasHops returns a boolean if a field has been set.
func (o *LensGraphRequest) HasHops() bool {
	if o != nil && !IsNil(o.Hops) {
		return true
	}

	return false
}

// SetHops gets a reference to the given int32 and assigns it to the Hops field.
func (o *LensGraphRequest) SetHops(v int32) {
	o.Hops = &v
}

func (o LensGraphRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LensGraphRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mode"] = o.Mode
	toSerialize["query"] = o.Query
	if !IsNil(o.Hops) {
		toSerialize["hops"] = o.Hops
	}
	return toSerialize, nil
}

func (o *LensGraphRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mode",
		"query",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLensGraphRequest := _LensGraphRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLensGraphRequest)

	if err != nil {
		return err
	}

	*o = LensGraphRequest(varLensGraphRequest)

	return err
}

type NullableLensGraphRequest struct {
	value *LensGraphRequest
	isSet bool
}

func (v NullableLensGraphRequest) Get() *LensGraphRequest {
	return v.value
}

func (v *NullableLensGraphRequest) Set(val *LensGraphRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLensGraphRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLensGraphRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLensGraphRequest(val *LensGraphRequest) *NullableLensGraphRequest {
	return &NullableLensGraphRequest{value: val, isSet: true}
}

func (v NullableLensGraphRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLensGraphRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


