/*
Fideo API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.4
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SignalPatternsTimeseriesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignalPatternsTimeseriesRequest{}

// SignalPatternsTimeseriesRequest struct for SignalPatternsTimeseriesRequest
type SignalPatternsTimeseriesRequest struct {
	SignalPatternsRequest
	// Time interval for timeseries data
	Interval string `json:"interval"`
	// Number of data points to return
	Count int32 `json:"count"`
}

type _SignalPatternsTimeseriesRequest SignalPatternsTimeseriesRequest

// NewSignalPatternsTimeseriesRequest instantiates a new SignalPatternsTimeseriesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignalPatternsTimeseriesRequest(interval string, count int32, email string) *SignalPatternsTimeseriesRequest {
	this := SignalPatternsTimeseriesRequest{}
	this.Email = email
	this.Interval = interval
	this.Count = count
	return &this
}

// NewSignalPatternsTimeseriesRequestWithDefaults instantiates a new SignalPatternsTimeseriesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignalPatternsTimeseriesRequestWithDefaults() *SignalPatternsTimeseriesRequest {
	this := SignalPatternsTimeseriesRequest{}
	return &this
}

// GetInterval returns the Interval field value
func (o *SignalPatternsTimeseriesRequest) GetInterval() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value
// and a boolean to check if the value has been set.
func (o *SignalPatternsTimeseriesRequest) GetIntervalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Interval, true
}

// SetInterval sets field value
func (o *SignalPatternsTimeseriesRequest) SetInterval(v string) {
	o.Interval = v
}

// GetCount returns the Count field value
func (o *SignalPatternsTimeseriesRequest) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *SignalPatternsTimeseriesRequest) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *SignalPatternsTimeseriesRequest) SetCount(v int32) {
	o.Count = v
}

func (o SignalPatternsTimeseriesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignalPatternsTimeseriesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedSignalPatternsRequest, errSignalPatternsRequest := json.Marshal(o.SignalPatternsRequest)
	if errSignalPatternsRequest != nil {
		return map[string]interface{}{}, errSignalPatternsRequest
	}
	errSignalPatternsRequest = json.Unmarshal([]byte(serializedSignalPatternsRequest), &toSerialize)
	if errSignalPatternsRequest != nil {
		return map[string]interface{}{}, errSignalPatternsRequest
	}
	toSerialize["interval"] = o.Interval
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *SignalPatternsTimeseriesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"interval",
		"count",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignalPatternsTimeseriesRequest := _SignalPatternsTimeseriesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSignalPatternsTimeseriesRequest)

	if err != nil {
		return err
	}

	*o = SignalPatternsTimeseriesRequest(varSignalPatternsTimeseriesRequest)

	return err
}

type NullableSignalPatternsTimeseriesRequest struct {
	value *SignalPatternsTimeseriesRequest
	isSet bool
}

func (v NullableSignalPatternsTimeseriesRequest) Get() *SignalPatternsTimeseriesRequest {
	return v.value
}

func (v *NullableSignalPatternsTimeseriesRequest) Set(val *SignalPatternsTimeseriesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSignalPatternsTimeseriesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSignalPatternsTimeseriesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignalPatternsTimeseriesRequest(val *SignalPatternsTimeseriesRequest) *NullableSignalPatternsTimeseriesRequest {
	return &NullableSignalPatternsTimeseriesRequest{value: val, isSet: true}
}

func (v NullableSignalPatternsTimeseriesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignalPatternsTimeseriesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


