/*
Fideo API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.4
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
)

// checks if the StatusResponseWithMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatusResponseWithMessage{}

// StatusResponseWithMessage struct for StatusResponseWithMessage
type StatusResponseWithMessage struct {
	Message *string `json:"message,omitempty"`
	Status *int32 `json:"status,omitempty"`
	Code *string `json:"code,omitempty"`
}

// NewStatusResponseWithMessage instantiates a new StatusResponseWithMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatusResponseWithMessage() *StatusResponseWithMessage {
	this := StatusResponseWithMessage{}
	return &this
}

// NewStatusResponseWithMessageWithDefaults instantiates a new StatusResponseWithMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatusResponseWithMessageWithDefaults() *StatusResponseWithMessage {
	this := StatusResponseWithMessage{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *StatusResponseWithMessage) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatusResponseWithMessage) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *StatusResponseWithMessage) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *StatusResponseWithMessage) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *StatusResponseWithMessage) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatusResponseWithMessage) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *StatusResponseWithMessage) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *StatusResponseWithMessage) SetStatus(v int32) {
	o.Status = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *StatusResponseWithMessage) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatusResponseWithMessage) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *StatusResponseWithMessage) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *StatusResponseWithMessage) SetCode(v string) {
	o.Code = &v
}

func (o StatusResponseWithMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatusResponseWithMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

type NullableStatusResponseWithMessage struct {
	value *StatusResponseWithMessage
	isSet bool
}

func (v NullableStatusResponseWithMessage) Get() *StatusResponseWithMessage {
	return v.value
}

func (v *NullableStatusResponseWithMessage) Set(val *StatusResponseWithMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusResponseWithMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusResponseWithMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusResponseWithMessage(val *StatusResponseWithMessage) *NullableStatusResponseWithMessage {
	return &NullableStatusResponseWithMessage{value: val, isSet: true}
}

func (v NullableStatusResponseWithMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusResponseWithMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


