/*
Fideo API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.3
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
)

// checks if the Email type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Email{}

// Email struct for Email
type Email struct {
	FirstSeenMs *int64 `json:"firstSeenMs,omitempty"`
	LastSeenMs *int64 `json:"lastSeenMs,omitempty"`
	Observations *int32 `json:"observations,omitempty"`
	Confidence *float64 `json:"confidence,omitempty"`
	Value *string `json:"value,omitempty"`
	Md5 *string `json:"md5,omitempty"`
	Sha1 *string `json:"sha1,omitempty"`
	Sha256 *string `json:"sha256,omitempty"`
	Label *string `json:"label,omitempty"`
	Activity *float64 `json:"activity,omitempty"`
}

// NewEmail instantiates a new Email object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmail() *Email {
	this := Email{}
	return &this
}

// NewEmailWithDefaults instantiates a new Email object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailWithDefaults() *Email {
	this := Email{}
	return &this
}

// GetFirstSeenMs returns the FirstSeenMs field value if set, zero value otherwise.
func (o *Email) GetFirstSeenMs() int64 {
	if o == nil || IsNil(o.FirstSeenMs) {
		var ret int64
		return ret
	}
	return *o.FirstSeenMs
}

// GetFirstSeenMsOk returns a tuple with the FirstSeenMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Email) GetFirstSeenMsOk() (*int64, bool) {
	if o == nil || IsNil(o.FirstSeenMs) {
		return nil, false
	}
	return o.FirstSeenMs, true
}

// HasFirstSeenMs returns a boolean if a field has been set.
func (o *Email) HasFirstSeenMs() bool {
	if o != nil && !IsNil(o.FirstSeenMs) {
		return true
	}

	return false
}

// SetFirstSeenMs gets a reference to the given int64 and assigns it to the FirstSeenMs field.
func (o *Email) SetFirstSeenMs(v int64) {
	o.FirstSeenMs = &v
}

// GetLastSeenMs returns the LastSeenMs field value if set, zero value otherwise.
func (o *Email) GetLastSeenMs() int64 {
	if o == nil || IsNil(o.LastSeenMs) {
		var ret int64
		return ret
	}
	return *o.LastSeenMs
}

// GetLastSeenMsOk returns a tuple with the LastSeenMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Email) GetLastSeenMsOk() (*int64, bool) {
	if o == nil || IsNil(o.LastSeenMs) {
		return nil, false
	}
	return o.LastSeenMs, true
}

// HasLastSeenMs returns a boolean if a field has been set.
func (o *Email) HasLastSeenMs() bool {
	if o != nil && !IsNil(o.LastSeenMs) {
		return true
	}

	return false
}

// SetLastSeenMs gets a reference to the given int64 and assigns it to the LastSeenMs field.
func (o *Email) SetLastSeenMs(v int64) {
	o.LastSeenMs = &v
}

// GetObservations returns the Observations field value if set, zero value otherwise.
func (o *Email) GetObservations() int32 {
	if o == nil || IsNil(o.Observations) {
		var ret int32
		return ret
	}
	return *o.Observations
}

// GetObservationsOk returns a tuple with the Observations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Email) GetObservationsOk() (*int32, bool) {
	if o == nil || IsNil(o.Observations) {
		return nil, false
	}
	return o.Observations, true
}

// HasObservations returns a boolean if a field has been set.
func (o *Email) HasObservations() bool {
	if o != nil && !IsNil(o.Observations) {
		return true
	}

	return false
}

// SetObservations gets a reference to the given int32 and assigns it to the Observations field.
func (o *Email) SetObservations(v int32) {
	o.Observations = &v
}

// GetConfidence returns the Confidence field value if set, zero value otherwise.
func (o *Email) GetConfidence() float64 {
	if o == nil || IsNil(o.Confidence) {
		var ret float64
		return ret
	}
	return *o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Email) GetConfidenceOk() (*float64, bool) {
	if o == nil || IsNil(o.Confidence) {
		return nil, false
	}
	return o.Confidence, true
}

// HasConfidence returns a boolean if a field has been set.
func (o *Email) HasConfidence() bool {
	if o != nil && !IsNil(o.Confidence) {
		return true
	}

	return false
}

// SetConfidence gets a reference to the given float64 and assigns it to the Confidence field.
func (o *Email) SetConfidence(v float64) {
	o.Confidence = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *Email) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Email) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *Email) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *Email) SetValue(v string) {
	o.Value = &v
}

// GetMd5 returns the Md5 field value if set, zero value otherwise.
func (o *Email) GetMd5() string {
	if o == nil || IsNil(o.Md5) {
		var ret string
		return ret
	}
	return *o.Md5
}

// GetMd5Ok returns a tuple with the Md5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Email) GetMd5Ok() (*string, bool) {
	if o == nil || IsNil(o.Md5) {
		return nil, false
	}
	return o.Md5, true
}

// HasMd5 returns a boolean if a field has been set.
func (o *Email) HasMd5() bool {
	if o != nil && !IsNil(o.Md5) {
		return true
	}

	return false
}

// SetMd5 gets a reference to the given string and assigns it to the Md5 field.
func (o *Email) SetMd5(v string) {
	o.Md5 = &v
}

// GetSha1 returns the Sha1 field value if set, zero value otherwise.
func (o *Email) GetSha1() string {
	if o == nil || IsNil(o.Sha1) {
		var ret string
		return ret
	}
	return *o.Sha1
}

// GetSha1Ok returns a tuple with the Sha1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Email) GetSha1Ok() (*string, bool) {
	if o == nil || IsNil(o.Sha1) {
		return nil, false
	}
	return o.Sha1, true
}

// HasSha1 returns a boolean if a field has been set.
func (o *Email) HasSha1() bool {
	if o != nil && !IsNil(o.Sha1) {
		return true
	}

	return false
}

// SetSha1 gets a reference to the given string and assigns it to the Sha1 field.
func (o *Email) SetSha1(v string) {
	o.Sha1 = &v
}

// GetSha256 returns the Sha256 field value if set, zero value otherwise.
func (o *Email) GetSha256() string {
	if o == nil || IsNil(o.Sha256) {
		var ret string
		return ret
	}
	return *o.Sha256
}

// GetSha256Ok returns a tuple with the Sha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Email) GetSha256Ok() (*string, bool) {
	if o == nil || IsNil(o.Sha256) {
		return nil, false
	}
	return o.Sha256, true
}

// HasSha256 returns a boolean if a field has been set.
func (o *Email) HasSha256() bool {
	if o != nil && !IsNil(o.Sha256) {
		return true
	}

	return false
}

// SetSha256 gets a reference to the given string and assigns it to the Sha256 field.
func (o *Email) SetSha256(v string) {
	o.Sha256 = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *Email) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Email) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *Email) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *Email) SetLabel(v string) {
	o.Label = &v
}

// GetActivity returns the Activity field value if set, zero value otherwise.
func (o *Email) GetActivity() float64 {
	if o == nil || IsNil(o.Activity) {
		var ret float64
		return ret
	}
	return *o.Activity
}

// GetActivityOk returns a tuple with the Activity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Email) GetActivityOk() (*float64, bool) {
	if o == nil || IsNil(o.Activity) {
		return nil, false
	}
	return o.Activity, true
}

// HasActivity returns a boolean if a field has been set.
func (o *Email) HasActivity() bool {
	if o != nil && !IsNil(o.Activity) {
		return true
	}

	return false
}

// SetActivity gets a reference to the given float64 and assigns it to the Activity field.
func (o *Email) SetActivity(v float64) {
	o.Activity = &v
}

func (o Email) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Email) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstSeenMs) {
		toSerialize["firstSeenMs"] = o.FirstSeenMs
	}
	if !IsNil(o.LastSeenMs) {
		toSerialize["lastSeenMs"] = o.LastSeenMs
	}
	if !IsNil(o.Observations) {
		toSerialize["observations"] = o.Observations
	}
	if !IsNil(o.Confidence) {
		toSerialize["confidence"] = o.Confidence
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Md5) {
		toSerialize["md5"] = o.Md5
	}
	if !IsNil(o.Sha1) {
		toSerialize["sha1"] = o.Sha1
	}
	if !IsNil(o.Sha256) {
		toSerialize["sha256"] = o.Sha256
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Activity) {
		toSerialize["activity"] = o.Activity
	}
	return toSerialize, nil
}

type NullableEmail struct {
	value *Email
	isSet bool
}

func (v NullableEmail) Get() *Email {
	return v.value
}

func (v *NullableEmail) Set(val *Email) {
	v.value = val
	v.isSet = true
}

func (v NullableEmail) IsSet() bool {
	return v.isSet
}

func (v *NullableEmail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmail(val *Email) *NullableEmail {
	return &NullableEmail{value: val, isSet: true}
}

func (v NullableEmail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


