/*
Fideo Production API

Fideo Intelligence offers an identity intelligence product that protects the public good. - [Fideo Privacy Policy](https://www.fideo.ai/privacy-policy/)

API version: 1.0.4
Contact: support@fideo.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fideo

import (
	"encoding/json"
)

// checks if the BetaSignalsPatternsSummaryPost400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BetaSignalsPatternsSummaryPost400Response{}

// BetaSignalsPatternsSummaryPost400Response struct for BetaSignalsPatternsSummaryPost400Response
type BetaSignalsPatternsSummaryPost400Response struct {
	Error *string `json:"error,omitempty"`
}

// NewBetaSignalsPatternsSummaryPost400Response instantiates a new BetaSignalsPatternsSummaryPost400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBetaSignalsPatternsSummaryPost400Response() *BetaSignalsPatternsSummaryPost400Response {
	this := BetaSignalsPatternsSummaryPost400Response{}
	return &this
}

// NewBetaSignalsPatternsSummaryPost400ResponseWithDefaults instantiates a new BetaSignalsPatternsSummaryPost400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBetaSignalsPatternsSummaryPost400ResponseWithDefaults() *BetaSignalsPatternsSummaryPost400Response {
	this := BetaSignalsPatternsSummaryPost400Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *BetaSignalsPatternsSummaryPost400Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BetaSignalsPatternsSummaryPost400Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *BetaSignalsPatternsSummaryPost400Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *BetaSignalsPatternsSummaryPost400Response) SetError(v string) {
	o.Error = &v
}

func (o BetaSignalsPatternsSummaryPost400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BetaSignalsPatternsSummaryPost400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableBetaSignalsPatternsSummaryPost400Response struct {
	value *BetaSignalsPatternsSummaryPost400Response
	isSet bool
}

func (v NullableBetaSignalsPatternsSummaryPost400Response) Get() *BetaSignalsPatternsSummaryPost400Response {
	return v.value
}

func (v *NullableBetaSignalsPatternsSummaryPost400Response) Set(val *BetaSignalsPatternsSummaryPost400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableBetaSignalsPatternsSummaryPost400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableBetaSignalsPatternsSummaryPost400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBetaSignalsPatternsSummaryPost400Response(val *BetaSignalsPatternsSummaryPost400Response) *NullableBetaSignalsPatternsSummaryPost400Response {
	return &NullableBetaSignalsPatternsSummaryPost400Response{value: val, isSet: true}
}

func (v NullableBetaSignalsPatternsSummaryPost400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBetaSignalsPatternsSummaryPost400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


